import 'dotenv/config'

export const env = {
  BUILD_MODE: process.env.BUILD_MODE,
  MONGODB_URI: process.env.MONGODB_URI,
  DATABASE_NAME: process.env.DATABASE_NAME,
  APP_NAME: process.env.APP_HOST,
  APP_PORT: process.env.APP_PORT,
  WEBSITE_DOMAIN_DEV: process.env.WEBSITE_DOMAIN_DEV,
  WEBSITE_DOMAIN_PROD: process.env.WEBSITE_DOMAIN_PROD,

  API_DOMAIN_DEV: process.env.API_DOMAIN_DEV,
  API_DOMAIN_PROD: process.env.API_DOMAIN_PROD,

  EMAIL_USER: process.env.EMAIL_USER,
  EMAIL_PASSWORD: process.env.EMAIL_PASSWORD,
  ACCESS_TOKEN_PRIVATE_KEY: process.env.ACCESS_TOKEN_PRIVATE_KEY,
  ACCESS_TOKEN_LIFE: process.env.ACCESS_TOKEN_LIFE,
  REFRESH_TOKEN_PRIVATE_KEY: process.env.REFRESH_TOKEN_PRIVATE_KEY,
  REFRESH_TOKEN_LIFE: process.env.REFRESH_TOKEN_LIFE,
  CLOUD_NAME: process.env.CLOUD_NAME,
  CLOUD_KEY: process.env.CLOUD_KEY,
  CLOUD_SECRET: process.env.CLOUD_SECRET,
    // GOOGLE
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,

  // FACEBOOK
  FACEBOOK_CLIENT_ID: process.env.FACEBOOK_CLIENT_ID,
  FACEBOOK_CLIENT_SECRET: process.env.FACEBOOK_CLIENT_SECRET,

   // GHN
  GHN_TOKEN: process.env.GHN_TOKEN,
  GHN_SHOP_ID: process.env.GHN_SHOP_ID,
  GHN_API_URL: process.env.GHN_API_URL,

  GHN_FROM_DISTRICT_ID: process.env.GHN_FROM_DISTRICT_ID,
  GHN_FROM_WARD_CODE: process.env.GHN_FROM_WARD_CODE,

  GHN_SERVICE_ID: process.env.GHN_SERVICE_ID,
  GHN_SERVICE_TYPE_ID: process.env.GHN_SERVICE_TYPE_ID,

  GHN_DEFAULT_WEIGHT: process.env.GHN_DEFAULT_WEIGHT,
  GHN_DEFAULT_LENGTH: process.env.GHN_DEFAULT_LENGTH,
  GHN_DEFAULT_WIDTH: process.env.GHN_DEFAULT_WIDTH,
  GHN_DEFAULT_HEIGHT: process.env.GHN_DEFAULT_HEIGHT,
  
  GHN_FALLBACK_FEE: process.env.GHN_FALLBACK_FEE,

  // Python Recommendation Microservice
  RECOMMENDATION_SERVICE_URL_DEV: process.env.RECOMMENDATION_SERVICE_URL_DEV,
  RECOMMENDATION_SERVICE_URL_PROD: process.env.RECOMMENDATION_SERVICE_URL_PROD,

  // PayOS Payment Gateway
  PAYOS_CLIENT_ID: process.env.PAYOS_CLIENT_ID,
  PAYOS_API_KEY: process.env.PAYOS_API_KEY,
  PAYOS_CHECKSUM_KEY: process.env.PAYOS_CHECKSUM_KEY,

  ORDER_AUTO_COMPLETE_DAYS: process.env.ORDER_AUTO_COMPLETE_DAYS,

  SYSTEM_ROLE_IDS: process.env.SYSTEM_ROLE_IDS,

  // Groq AI (legacy)
  // GROQ_API_KEY: process.env.GROQ_API_KEY,

  // Gemini AI — API Key Pool (legacy)
  // GEMINI_API_KEY: process.env.GEMINI_API_KEY,
  // GEMINI_API_KEY_1: process.env.GEMINI_API_KEY_1,
  // GEMINI_API_KEY_2: process.env.GEMINI_API_KEY_2,
  // GEMINI_API_KEY_3: process.env.GEMINI_API_KEY_3,

  // OpenAI — Production Chatbot (Intent Router + RAG Pipeline)
  OPENAI_API_KEY: process.env.OPENAI_API_KEY,

  // Redis — Embedding Cache
  REDIS_URL: process.env.REDIS_URL,
}
